server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final_app
    password: Weyx_man7558
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true